TravelCo/TravelCo/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path("admin/", admin.site.urls),
    path("accounts/", include("accounts.urls", namespace="accounts")),
    path("", include("tours.urls", namespace="tours")),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

TravelCo/tours/urls.py
from django.urls import path
from . import views


app_name = "tours"

urlpatterns = [
    path("", views.list, name="list"),
    path("<int:tour_id>/", views.detail, name="detail"),
]

TravelCo/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %}{% endblock %}</title>
    <link rel="stylesheet" href="{% static 'css/base.css' %}">
</head>
<body>
    <nav class="navbar">
        <div class="navbar__brand">
            <a class="navbar__link" href="{% url 'tours:list' %}">TravelCo</a>
        </div>
        <div class="navbar__links">
                {% if request.user.is_authenticated %}
                        <a class="navbar__link" href="#">Profile</a>
                        <form method="post" action="#">
                            {% csrf_token %}
                            <button class="navbar__button">Logout</button>
                        </form>
                {% else %}
                    <a class="navbar__link" href="#">Register</a>
                    <a class="navbar__link" href="#">Login</a>
                {% endif %}
        </div>
    </nav>

    <div class="container">
        {% block content %}
        {% endblock %}
    </div>
</body>
</html>