TravelCo/TravelCo/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path("admin/", admin.site.urls),
    path("accounts/", include("accounts.urls", namespace="accounts")),
    path("", include("tours.urls", namespace="tours")),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

TravelCo/tours/urls.py
from django.urls import path
from . import views


app_name = "tours"

urlpatterns = [
    path("", views.list, name="list"),
    path("<int:tour_id>/", views.detail, name="detail"),
]

TravelCo/accounts/models.py
from django.contrib.auth.models import AbstractBaseUser, PermissionsMixin
from django.db import models
from django.core.mail import send_mail

import random
from django.utils import timezone

from .manager import CustomUserManager


class User(AbstractBaseUser, PermissionsMixin):
    email = models.EmailField(unique=True, blank=True, null=True)
    phone = models.CharField(max_length=12, unique=True, blank=True, null=True)
    verification_code = models.CharField(max_length=6, blank=True, null=True)

    is_active = models.BooleanField(default=True)
    is_staff = models.BooleanField(default=False)

    objects = CustomUserManager()

    # Define the field to use as the unique identifier for authentication
    USERNAME_FIELD = "email"  # Or "phone"
    REQUIRED_FIELDS = []

    # Constants for verification code
    VERIFICATION_CODE_EXPIRATION_TIME = 300  # 5 minutes (in seconds)
    MAX_VERIFICATION_ATTEMPTS = 3
    VERIFICATION_ATTEMPT_WINDOW = 3600  # 1 hour (in seconds)

    # Fields for tracking verification attempts
    verification_code_timestamp = models.DateTimeField(null=True, blank=True)
    verification_attempts = models.PositiveIntegerField(default=0)
    last_verification_attempt = models.DateTimeField(null=True, blank=True)

    def __str__(self):
        return self.email or self.phone

    def generate_verification_code(self):
        """Generate a random 6-digit verification code."""
        code = random.randint(100_000, 999_999)
        self.verification_code = code
        self.verification_code_timestamp = timezone.now()
        self.save()

    def verify_verification_code(self, code):
        """Verify the provided verification code."""
        if (
            self.verification_code == code
            and self.verification_code_timestamp
            and timezone.now() - self.verification_code_timestamp
            <= timezone.timedelta(seconds=self.VERIFICATION_CODE_EXPIRATION_TIME)
        ):
            self.verification_attempts = 0  # Reset attempts on successful verification
            self.save()
            return True
        return False

    def record_verification_attempt(self):
        """Record a verification attempt."""
        if (
            not self.last_verification_attempt
            or timezone.now() - self.last_verification_attempt
            >= timezone.timedelta(seconds=self.VERIFICATION_ATTEMPT_WINDOW)
        ):
            self.verification_attempts = 1
        else:
            self.verification_attempts += 1
        self.last_verification_attempt = timezone.now()
        self.save()

    def is_verification_attempts_exceeded(self):
        """Check if verification attempts exceeded."""
        return self.verification_attempts >= self.MAX_VERIFICATION_ATTEMPTS

    def send_verification_code(self):
        """Send the verification code via email."""
        code = self.generate_verification_code()

        subject = "Verification Code"
        message = f"Your verification code is: {code}"
        from_email = "your_email@gmail.com"  # Update with your email
        to_email = self.email

        send_mail(subject, message, from_email, [to_email])


class Profile(models.Model):
    user = models.OneToOneField(User, related_name='profile',
                                on_delete=models.CASCADE)
    first_name = models.CharField(max_length=150, blank=True)
    last_name = models.CharField(max_length=150, blank=True)
    address = models.CharField(max_length=250, blank=True)

    def get_full_name(self):
        """Return the full name of the user."""
        return f"{self.first_name} {self.last_name}"

    def get_short_name(self):
        """Return the short name of the user."""
        return self.first_name

TravelCo/tours/models.py
from django.db import models
from django.conf import settings
from django.utils.text import slugify


class Category(models.Model):
    name = models.CharField(max_length=200)
    slug = models.SlugField(max_length=200, unique=True)

    class Meta:
        ordering = ["name"]
        indexes = [
            models.Index(fields=["name"]),
        ]

    def __str__(self) -> str:
        return self.name


class Tour(models.Model):
    title = models.CharField(max_length=50)
    slug = models.SlugField(max_length=50, blank=True, unique=True)
    image = models.ImageField(blank=True, upload_to="tour/%Y/%m/%d")
    description = models.TextField(blank=True)
    duration = models.PositiveIntegerField()
    price = models.DecimalField(max_digits=10, decimal_places=2)
    available = models.BooleanField(default=True)
    capacity = models.PositiveIntegerField()

    category = models.ForeignKey(
        Category, related_name="tours", on_delete=models.RESTRICT
    )
    social_sharing = models.BooleanField(default=False)

    class Meta:
        ordering = ["-available"]
        indexes = [
            models.Index(fields=["id", "slug"]),
            models.Index(fields=["title"]),
            models.Index(fields=["-available"]),
        ]

    def __str__(self):
        return self.title

    def save(self, *args, **kwargs):
        if not self.slug:
            self.slug = slugify(self.title)
        super().save(*args, **kwargs)


class TourSchedule(models.Model):
    tour = models.ForeignKey(Tour, related_name="schedules",
                             on_delete=models.CASCADE)
    start_time = models.DateTimeField()
    end_time = models.DateTimeField()

    class Meta:
        ordering = ["start_time"]

    def __str__(self):
        return f"{self.start_time.strftime('%b %d, %Y %H:%M')} -\
                {self.end_time.strftime('%b %d, %Y %H:%M')}"


class Booking(models.Model):
    tour = models.ForeignKey(Tour, related_name="bookings",
                             on_delete=models.PROTECT)
    user = models.ForeignKey(settings.AUTH_USER_MODEL,
                             related_name="bookings",
                             on_delete=models.PROTECT)
    adults = models.PositiveIntegerField(default=1)
    children = models.PositiveIntegerField(default=0)
    babies = models.PositiveIntegerField(default=0)

    booking_date = models.DateTimeField(auto_now_add=True)
    paid = models.BooleanField(default=False)

    class Meta:
        ordering = ["booking_date"]

    def __str__(self):
        return f"{self.tour.title} - {self.user.username}"


class Promotion(models.Model):
    title = models.CharField(max_length=100)
    description = models.TextField()
    start_date = models.DateField()
    end_date = models.DateField()
    active = models.BooleanField(default=True)

    class Meta:
        ordering = ["active"]

    def __str__(self):
        return self.title

TravelCo/tours/forms.py
from django import forms
from .models import Booking, TourSchedule


class BookingForm(forms.ModelForm):
    tour_schedule = forms.ModelChoiceField(queryset=None, empty_label=None)

    class Meta:
        model = Booking
        fields = ["tour_schedule", "adults", "children", "babies"]

    def __init__(self, *args, **kwargs):
        tour = kwargs.pop("tour")
        super().__init__(*args, **kwargs)
        self.fields["tour_schedule"].queryset = TourSchedule.objects.filter(tour=tour)

TravelCo/tours/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.db.models import F

from .models import Tour
from .forms import BookingForm


def list(request):
    tours = Tour.objects.all()
    return render(request, "list.html", {"tours": tours})


def detail(request, tour_id):
    tour = get_object_or_404(Tour, id=tour_id)
    if request.method == "POST":
        if request.user.is_authenticated:
            booking_form = BookingForm(request.POST, tour=tour)
            if booking_form.is_valid():
                booked = booking_form.save(commit=False)
                booked.tour = tour
                booked.user = request.user
                booked.save()

                # Update the tour's maximum capacity
                Tour.objects.filter(id=tour_id).update(
                    max_capacity=F("max_capacity")
                    - (booked.adults + booked.children + booked.babies)
                )

                return redirect("account:profile")
        else:
            # Store form data in session
            request.session["tour_id"] = tour_id
            request.session["form_data"] = request.POST.dict()
            return redirect("account:login")
    else:
        booking_form = BookingForm(tour=tour)
    return render(request, "detail.html",
                  {"tour": tour, "form": booking_form})

TravelCo/tours/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %}{% endblock %}</title>
    <link rel="stylesheet" href="{% static 'css/base.css' %}">
</head>
<body>
    <nav class="navbar">
        <div class="navbar__brand">
            <a class="navbar__link" href="{% url 'tour:list' %}">TravelCo</a>
        </div>
        <div class="navbar__links">
                {% if request.user.is_authenticated %}
                        <a class="navbar__link" href="{% url 'account:profile' %}">Profile</a>
                        <form method="post" action="{% url 'account:logout' %}">
                            {% csrf_token %}
                            <button class="navbar__button">Logout</button>
                        </form>
                {% else %}
                    <a class="navbar__link" href="{% url 'account:register' %}">Register</a>
                    <a class="navbar__link" href="{% url 'account:login' %}">Login</a>
                {% endif %}
        </div>
    </nav>

    <div class="container">
        {% block content %}
        {% endblock %}
    </div>
</body>
</html>

TravelCo/tours/templates/detail.html
{% extends "base.html" %}
{% load static %}

{% block title %}{{ tour.title }}{% endblock %}

{% block content %}
    <div class="tour-detail">
        <div class="tour-image-detail">
            {% if tour.image %}
                <img src="{{ tour.image.url }}" alt="Tour Image">
            {% else %}
                <img src="{% static 'image/no_image.png' %}" alt="Placeholder Image">
            {% endif %}
        </div>
        <div class="tour-info">
            <h2 class="tour-title-detail">{{ tour.title }}</h2>
            <p class="tour-description">{{ tour.description }}</p>
            <p class="tour-duration">Duration: {{ tour.duration }} day{{ tour.duration|pluralize }}</p>
            <p class="tour-dates">Dates: {{ tour.start_date|date:"F j, Y" }} - {{ tour.end_date|date:"F j, Y" }}</p>
            <p class="tour-price">Price: {{ tour.price }}</p>
            <p class="tour-capacity">Capacity: {{ tour.max_capacity }}</p>
        </div>
        <div class="tour-form">
            <form method="post">
                {% csrf_token %}
                <div class="tour-schedule">
                    <label class="tour-schedule-label" for="id_tour_schedule">
                        Tour Schedule
                    </label>
                    {{ form.tour_schedule }}
                </div>
                <div class="tour-num">
                    <label class="tour-num-label" for="id_adults">
                        Number of Adults
                    </label>
                    {{ form.adults }}
                </div>
                <div class="tour-num">
                    <label class="tour-num-label" for="id_children">
                        Number of Children
                    </label>
                    {{ form.children }}
                </div>
                <div class="tour-num">
                    <label class="tour-num-label" for="id_babies">
                        Number of Babies
                    </label>
                    {{ form.babies }}
                </div>
                <div class="tour-submit">
                    <button type="submit" class="tour-submit-but">Book Now</button>
                </div>
            </form>
        </div>
    </div>
{% endblock %}

TravelCo/tours/templates/list.html
{% extends "base.html" %}
{% load static %}
{% block title %}Tours{% endblock %}
{% block content %}
<div class="tour-list">
    {% for tour in tours %}
        <div class="tour-card">
            <a href="{% url 'tour:detail' tour.id %}">
                <div class="tour-image">
                    {% if tour.image %}
                        <img src="{{ tour.image.url }}" alt="Tour Image">
                    {% else %}
                        <img src="{% static 'image/no_image.png' %}" alt="Placeholder Image">
                    {% endif %}
                </div>
                <div class="tour-details">
                    <h2 class="tour-title">{{ tour.title }}</h2>
                    <p class="tour-description">{{ tour.description }}</p>
                    <p class="tour-duration">Duration: {{ tour.duration }} day{{ tour.duration|pluralize }}</p>
                    <p class="tour-dates">Dates: {{ tour.start_date|date:"F j, Y" }} - {{ tour.end_date|date:"F j, Y" }}</p>
                    <p class="tour-price">Price: {{ tour.price }}</p>
                    <p class="tour-availability"> 
                        {% if tour.available %}
                            <p class="tour-true">Available</p>
                        {% else %}
                            <p class="tour-false">Not Available</p>
                        {% endif %}
                    </p>
                    <p class="tour-capacity">Capacity: {{ tour.max_capacity }}</p>
                </div>
            </a>
        </div>
    {% endfor %}
</div>
{% endblock %}